### ISSUE TITLE
SmartOS own build server fails git clone: destination... already exists and is not an empty directory.

### ISSUE THREAD

**Issue by doublerebel** [Distelli/Support#2]
Hello,

I attempted to use one of my Joyent Public Cloud SmartOS instances to build today, and the build fails with:

```sh
Identity added: (stdin) ((stdin))
fatal: destination path '/distelli/tasks/d1614-33941' already exists and is not an empty directory.
FAILED:	git clone --depth 50 ssh://hg@bitbucket.org/doublerebel/<REPO> /distelli/tasks/d1614-33941 -b master
```
I was curious how this could happen, so I wrote a little nodejs script to `fs.watch()` the **/distelli/tasks** directory.  According to my watch, after the Distelli Agent creates the temporary build directory, it places a file named **.dtk** in the directory.   That would explain why git refuses to clone.

#### code to reproduce:
```sh
sudo npm install -g coffee-script
```

watch.coffee
```coffee
fs = require "fs"
{log} = console
path = "/distelli/tasks"

handler = (event, filename) ->
  log event
  log filename
  files = fs.readdirSync path
  for file in files
    file = path + "/" + file
    log file
    fd = fs.openSync file, "r"
    stats = fs.fstatSync fd
    if stats.isFile()
      contents = fs.readFileSync file
      log contents
    else if stats.isDirectory()
      subfiles = fs.readdirSync file
      log "subfiles count:", subfiles.length
      log subfile for subfile in subfiles
      fs.watch file, handler

fs.watch path, handler
```

```sh
coffee watch.coffee
<run a build from Distelli dashboard>
```

#### gives me output like:
```sh
change
null
/distelli/tasks/d1614-33950
subfiles count: 0
change
null
/distelli/tasks/d1614-33950
subfiles count: 1
.dtk
change
null
```

The Distelli Agent version is 3.63.

Thanks!

**Comment by doublerebel** [comment]
I should mention, first the agent threw errors about **/.ssh** not existing.  I created **/.ssh** with owner distelli and symlinked its **known_hosts** into **/home/distelli/.ssh/known_hosts** , but it's probably more correct if the agent uses **/home/distelli/.ssh/known_hosts** from the beginning.  **/home/distelli/.ssh** does not exist after distelli creates its homedir so it will have to create that directory.

**Comment by brimworks** [comment]
My first guess is that our version of libuv's uv_os_homedir() [1] function is returning the empty string and thus the ~/.dtk directory is mapped to the current directory .dtk (which in this instance was /distelli/tasks/d1614-33950). Perhaps libuv has had fixes for this recently. I can try to upgrade it.

Thanks,
-Brian

[1] http://docs.libuv.org/en/v1.x/misc.html#c.uv_os_homedir

**Comment by doublerebel** [comment]
@brimworks thanks for the fast sleuthing.  It looks like uv_os_homedir() is a relatively new feature: [libuv/libuv#11](https://github.com/libuv/libuv/issues/11)?

It appears that [the libuv unix implementation just uses **getpwuid_r**](https://github.com/cjihrig/libuv/commit/217f81b6a18f52322ddfdaf704e9057005e3d10d#diff-4429fa62e3d0385de0bebfcd93980332R1148).  Solaris has a slightly different implementation of **getpwuid_r** [that bit Curl as recently as July 2014](https://curl.haxx.se/mail/lib-2014-07/0169.html).  Perhaps libuv needs to be compiled with [flag **_POSIX_PTHREAD_SEMANTICS**](https://notmuchmail.org/pipermail/notmuch/2013/015676.html)?

If that flag fixes the issue we could file upstream with libuv.

**Comment by brimworks** [comment]
Updating to v1.9.0 doesn't appear to work... I'll see if I can find a fix and patch.

**Comment by brimworks** [comment]
(of libuv: https://github.com/libuv/libuv/releases/tag/v1.9.0)

**Comment by brimworks** [comment]
I take that back :). I now realize that I was using luajit FFI to dlopen/dlsym/call the getpwuid API. I should be able to fix this in the next release.

Thanks,
-Brian

**Comment by brimworks** [comment]
BTW, I also fixed the issue with MAC address on CoreOS always being "null" (string of 6 zeros):

https://github.com/libuv/libuv/pull/907

This should mean GUIDs will no longer contain a long string of zeros.

**Comment by brimworks** [comment]
...and my change is now contributed back to libuv:

https://github.com/libuv/libuv/commit/d75e334e34487575bcb46f6311fefbdc4849a564

I've got a new release of the agent for SmartOS with all this fixed, I'll be releasing that version soon.

Thanks,
-Brian

**Comment by doublerebel** [comment]
@brimworks Thanks for all your work on this, I finally just circled back and upgraded my workflow.  I am able to build on my SmartOS build server now using Distelli Agent 3.65.  This feature is huge for me to move forward, much appreciated!
